import test from 'node:test';
import assert from 'node:assert/strict';
import {KEY,initial,validate,parseBackup,previous,suggested,start,record,removeSet,finish,remaining,Repository} from '../dist/data.js';
class Storage{m=new Map();getItem(k){return this.m.get(k)??null;}setItem(k,v){if(this.fail)throw Error('quota');this.m.set(k,v);}}
test('record starts timer; supplement does not replace timer',()=>{const d=initial();start(d,d.plans[0].id);const m=d.active.movements[0];const s=record(d,m.id,9,40,true,1000);assert.equal(d.rest.end,91000);record(d,m.id,6,35,false,2000);assert.equal(d.rest.setID,s.id);assert.equal(m.sets.length,2);});
test('undo cancels only associated rest',()=>{const d=initial();start(d,d.plans[0].id);const m=d.active.movements[0],s=record(d,m.id,9,40),extra=record(d,m.id,6,35,false);removeSet(d,m.id,extra.id);assert.equal(d.rest.setID,s.id);removeSet(d,m.id,s.id);assert.equal(d.rest,null);});
test('historical corresponding weights and override',()=>{const d=initial();start(d,d.plans[0].id);let m=d.active.movements[0];record(d,m.id,9,40);record(d,m.id,8,35);finish(d);start(d,d.plans[0].id);m=d.active.movements[0];assert.equal(suggested(d,m),40);record(d,m.id,9,40);assert.equal(suggested(d,m),35);m.overrideWeight=42.5;assert.equal(suggested(d,m),42.5);});
test('unfinished training survives persisted reload',()=>{const storage=new Storage(),r=new Repository(storage);r.change(d=>start(d,d.plans[0].id));r.change(d=>record(d,d.active.movements[0].id,9,40));const next=new Repository(storage);assert.equal(next.db.active.movements[0].sets.length,1);assert.equal(next.db.rest.end,r.db.rest.end);});
test('write failure does not acknowledge a new set',()=>{const st=new Storage(),r=new Repository(st);r.change(d=>start(d,d.plans[0].id));st.fail=true;assert.throws(()=>r.change(d=>record(d,d.active.movements[0].id,9,40)));assert.equal(r.db.active.movements[0].sets.length,0);});
test('corrupt storage is protected from overwrite',()=>{const s=new Storage();s.setItem(KEY,'broken');const r=new Repository(s);assert.equal(r.writable,false);assert.throws(()=>r.change(()=>{}));assert.equal(s.getItem(KEY),'broken');});
test('snapshot protects history against renamed and deleted plans',()=>{const d=initial();start(d,d.plans[0].id);const m=d.active.movements[0],name=m.exercise.name;record(d,m.id,9,40);finish(d);d.plans[0].exercises[0].name='new';d.plans=[];assert.equal(d.history[0].movements[0].exercise.name,name);validate(d);});
test('native Swift backup timestamps migrate correctly',()=>{const d=initial();start(d,d.plans[0].id);record(d,d.active.movements[0].id,9,40);delete d.format;const original=d.active.started;d.active.started=d.active.started/1000-978307200;delete d.active.ended;for(const m of d.active.movements)for(const s of m.sets)s.date=s.date/1000-978307200;d.rest.end=d.rest.end/1000-978307200;const result=parseBackup(JSON.stringify(d));assert.ok(Math.abs(result.active.started-original)<1);assert.equal(result.active.movements[0].sets[0].reps,9);});
test('reject invalid backup without replacing existing record',()=>{const s=new Storage(),r=new Repository(s);r.change(()=>{});const before=s.getItem(KEY),bad=initial();bad.plans[0].exercises[0].reps=[8,8,10];assert.throws(()=>r.restore(bad));assert.equal(s.getItem(KEY),before);});
test('restore saves previous state and replaces atomically',()=>{const s=new Storage(),r=new Repository(s);r.change(()=>{});const before=s.getItem(KEY),next=initial();next.plans[0].name='Restored';r.restore(next);assert.equal(s.getItem(KEY+'.before-restore'),before);assert.equal(r.db.plans[0].name,'Restored');});
test('invalid set cannot corrupt current training',()=>{const st=new Storage(),r=new Repository(st);r.change(d=>start(d,d.plans[0].id));assert.throws(()=>r.change(d=>record(d,d.active.movements[0].id,0,40)));assert.equal(r.db.active.movements[0].sets.length,0);});
test('absolute deadline works after suspension',()=>{assert.equal(remaining({end:95000},65000),30);assert.equal(remaining({end:95000},100000),0);});
